import { Box } from "@mui/material";
import { FastField, FieldArray, Formik } from "formik";
import { Fragment, memo, useMemo } from "react";
import CommonStyles from "../../../../../Components/CommonStyles";
import CommonField from "../../../../../Components/CommonFields";
import CollapseArea from "../CollapseArea";
import { isArray } from "lodash";
import { v4 as uuid } from "uuid";
import { VariableTypeOptions } from "../LLMNode/SingleTab/Inputs";
import CommonIcons from "../../../../../Components/CommonIcons";

export const ResponseModeType = [
  {
    label: "Return variables, generated by the bot",
    value: "return_variables",
  },
];

const Parameters = () => {
  //! State
  const initialValues = useMemo(() => {
    return {
      responseMode: "return_variables",
      outputs: [
        {
          id: uuid(),
          parameterName: "",
          parameterValue: "",
        },
      ],
    };
  }, []);

  //! Function

  //! Render
  return (
    <Formik initialValues={initialValues} onSubmit={() => {}}>
      {({ values }) => {
        return (
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              marginTop: "20px",
            }}
          >
            <Box
              sx={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
              }}
            >
              <CommonStyles.Typography type="bold14">
                Select response type
              </CommonStyles.Typography>
              <FastField
                name="responseMode"
                component={CommonField.MuiSelectField}
                options={ResponseModeType}
                fullWidth
                sxContainer={{
                  maxWidth: "60%",
                }}
              />
            </Box>

            <CollapseArea label="Output variables">
              <FieldArray
                name="outputs"
                render={({ push, remove }) => {
                  return (
                    <Fragment>
                      <Box
                        sx={{
                          display: "grid",
                          gridTemplateColumns: "40% 50% 5%",
                          alignItems: "center",
                          gap: "10px",
                        }}
                      >
                        <CommonStyles.Typography
                          type="normal12"
                          color={"#bbbbbb"}
                        >
                          Parameter name
                        </CommonStyles.Typography>
                        <CommonStyles.Typography
                          type="normal12"
                          color={"#bbbbbb"}
                        >
                          Parameter value
                        </CommonStyles.Typography>
                        <Box></Box>
                        {isArray(values.outputs) &&
                          values.outputs.map((output, index) => {
                            return (
                              <Fragment key={output.id}>
                                <FastField
                                  name={`outputs.${index}.parameterName`}
                                  component={CommonField.InputField}
                                  placeholder="Enter parameter name"
                                />

                                <FastField
                                  name={`outputs.${index}.parameterValue`}
                                  component={CommonField.MuiSelectField}
                                  placeholder="Enter variable name"
                                  options={VariableTypeOptions}
                                  className="nodrag"
                                  fullWidth
                                />

                                <CommonStyles.Button
                                  isIcon
                                  color="error"
                                  onClick={() => remove(index)}
                                >
                                  <CommonIcons.Delete />
                                </CommonStyles.Button>
                              </Fragment>
                            );
                          })}
                      </Box>
                      <CommonStyles.Button
                      variant="outlined"
                        sx={{ marginTop: "20px" }}
                        startIcon={<CommonIcons.Add />}
                        onClick={() => {
                          push({
                            id: uuid(),
                            parameterName: "",
                            parameterValue: "",
                          });
                        }}
                      >
                        Add output variable
                      </CommonStyles.Button>
                    </Fragment>
                  );
                }}
              />
            </CollapseArea>
          </Box>
        );
      }}
    </Formik>
  );
};

export default memo(Parameters);
