# Build Phase
FROM node:18-alpine AS build

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install all dependencies (including dev)
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build


# Run Phase
FROM node:18-alpine

WORKDIR /app

# Copy only the package files to install production dependencies
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm install --only=production

RUN npm install -g serve

# Copy the built files from the build stage
COPY --from=build /app/dist /app/dist

# Start the application
CMD [ "serve", "-s", "dist"]
