export default {
  toggleTheme: "toggle-theme",

  LOADING_APP: "LOADING_APP",
  OPEN_DIALOG: "OPEN_DIALOG",

  //!  Knowledge
  REFETCH_FOLDER_KNOWLEDGE: "REFETCH_FOLDER_KNOWLEDGE",
  REFETCH_KNOWLEDGE_FILES: "REFETCH_KNOWLEDGE_FILES",

  //! Bot
  REFETCH_LIST_BOT: "REFETCH_LIST_BOT",
  REFETCH_BOT_DATA: "REFETCH_BOT_DATA",
  REFETCH_CONVERSATION: "REFETCH_CONVERSATION",
  REFETCH_LIST_CHAT: "REFETCH_LIST_CHAT",
  BOT_DATA: "BOT_DATA",
  LIST_CHAT: "LIST_CHAT",
  CONVERSATION : "CONVERSATION",
  OPEN_CONVERSATION: "OPEN_CONVERSATION",
  IS_BRANDNEW_CHAT: "IS_BRANDNEW_CHAT",
  OPEN_PERSONALPROMP: "OPEN_PERSONALPROMP",
  OPEN_CHAT: "OPEN_CHAT",
  VIEWPORT: 'VIEWPORT',
  HISTORY:"HISTORY",
  SAVE_HISTORY: "SAVE_HISTORY",
  ADD_NODE: "ADD_NODE",
  DISABLE_CIRCLE: "DISABLE_CIRCLE",

  //! User
  REFETCH_USER_DATA: "REFETCH_USER_DATA",

  //! React flow
  FLOW_NODES: "FLOW_NODES",
  FLOW_EDGES: "FLOW_EDGES",

  //! Community
  OPEN_DRAWER: "OPEN_DRAWER",


  //! Mock
  COMMUNITY_REACTION: "COMMUNITY_REACTION",
  COMMUNITY_COMMENT: "COMMUNITY_COMMENT",

} as const;
