export default {
  toggleTheme: "toggle-theme",

  LOADING_APP: "LOADING_APP",
  OPEN_DIALOG: "OPEN_DIALOG",

  //!  Knowledge
  REFETCH_FOLDER_KNOWLEDGE: "REFETCH_FOLDER_KNOWLEDGE",
  REFETCH_KNOWLEDGE_FILES: "REFETCH_KNOWLEDGE_FILES",

  //! Bot
  REFETCH_LIST_BOT: "REFETCH_LIST_BOT",
  REFETCH_BOT_DATA: "REFETCH_BOT_DATA",
  BOT_DATA: "BOT_DATA",

  //! User
  REFETCH_USER_DATA: "REFETCH_USER_DATA",

  //! React flow
  FLOW_NODES: "FLOW_NODES",
  FLOW_EDGES: "FLOW_EDGES",


  //! Mock
  COMMUNITY_REACTION: "COMMUNITY_REACTION",
  COMMUNITY_COMMENT: "COMMUNITY_COMMENT",

} as const;
