import { Box, TextField, Tooltip, useTheme } from "@mui/material";
import { useState } from "react";
import { Fragment } from "react/jsx-runtime";
import CommonStyles from "../../../Components/CommonStyles";
import CommonIcons from "../../../Components/CommonIcons";

import Coze from "../../../assets/coze.png";
const PreviewChat = () => {
  //! State
  const [inputValue, setInputValue] = useState("");
  const theme: any = useTheme();
  //! Function

  //! Render
  return (
    <Fragment>
      <Box
        sx={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: "translate(-50%,-50%)",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <img
          src={Coze}
          alt="coze"
          style={{ height: "100px", width: "100px", borderRadius: "12px" }}
        />
        <CommonStyles.Typography type="semiBold16" color={theme.colors.primary}>
          Coze
        </CommonStyles.Typography>
      </Box>
      <Box
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          width: "100%",
          position: "absolute",
          left: "50%",
          transform: "translateX(-50%)",
          bottom: "0",
          height: "80px",
        }}
      >
        <Box
          sx={{
            display: "flex",
            gap: "12px",
            width: "100%",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <CommonStyles.Button isIcon>
            <Tooltip title="New chat">
              <CommonIcons.AddComment fontSize="small" />
            </Tooltip>
          </CommonStyles.Button>
          <Box
            sx={{
              width: "90%",
              border: "solid 1px #ccc",
              height: "fit-content",
              display: "flex",
              alignItems: "center",
              padding: "0 12px 0 20px",
              borderRadius: "24px",
              background: "#fff",
              ".MuiInputBase-root": {
                padding: 0,
              },
            }}
          >
            <TextField
              fullWidth
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              inputProps={{
                sx: {
                  padding: "12px 12px 12px 0",
                },
              }}
              sx={{
                padding: 0,
                fieldset: {
                  border: "none",
                },
              }}
            />
            <CommonStyles.Button isIcon disabled={!inputValue}>
              <Tooltip title="Send" placement="top-start">
                <CommonIcons.Send
                  fontSize="small"
                  color={inputValue ? "primary" : "disabled"}
                />
              </Tooltip>
            </CommonStyles.Button>
          </Box>
        </Box>
        <CommonStyles.Typography
          type="normal12"
          color={theme.colors.custom.normalColorTypo}
        >
          The content is generated by AI and it's for reference only.
        </CommonStyles.Typography>
      </Box>
    </Fragment>
  );
};

export default PreviewChat;
