import { Box, TextField, Tooltip } from "@mui/material";
import CommonIcons from "../../../Components/CommonIcons";
import CommonStyles from "../../../Components/CommonStyles";
import { useState } from "react";

interface IInputChat {}

function InputChat(props: IInputChat) {
  //! State
  const {} = props;
  const [inputValue, setInputValue] = useState("");

  //! Function

  //! Render
  return (
    <Box
      sx={{
        height: "100px",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        background: "#f5f6f8",
        width: "100%",
        position: "relative",
        "&:before": {
          content: '""',
          position: "absolute",
          top: "-48px",
          height: "48px",
          width: "100%",
          background:
            "linear-gradient(180deg, hsla(0, 0%, 100%, 0) 0, #f5f6f8 50%)",
        },
      }}
    >
      <Box
        sx={{
          display: "flex",
          gap: "12px",
          width: "100%",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <CommonStyles.Button isIcon>
          <Tooltip title="New chat">
            <CommonIcons.AddComment fontSize="small" />
          </Tooltip>
        </CommonStyles.Button>
        <Box
          sx={{
            width: "50%",
            border: "solid 1px #ccc",
            height: "fit-content",
            display: "flex",
            alignItems: "center",
            padding: "0 12px 0 20px",
            borderRadius: "24px",
            background: "#fff",
            ".MuiInputBase-root": {
              padding: 0,
            },
          }}
        >
          <TextField
            fullWidth
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            inputProps={{
              sx: {
                padding: "12px 12px 12px 0",
              },
            }}
            sx={{
              padding: 0,
              fieldset: {
                border: "none",
              },
            }}
          />
          <CommonStyles.Button isIcon disabled={!inputValue}>
            <Tooltip title="Send" placement="top-start">
              <CommonIcons.Send
                fontSize="small"
                color={inputValue ? "primary" : "disabled"}
              />
            </Tooltip>
          </CommonStyles.Button>
        </Box>
      </Box>
      <CommonStyles.Typography type="normal12" sx={{ color: "#ccc" }}>
        The content is generated by AI and it's for reference only.
      </CommonStyles.Typography>
    </Box>
  );
}

export default InputChat;
